// Auto-generated by scripts/split-locales.js — DO NOT EDIT THE BOILERPLATE.
// Namespace: business
// Language: zh-CN
// Add new keys for this namespace below. Keep keys consistent across
// languages — run `node scripts/check-i18n-keys.js` before commit.
// eslint-disable-next-line import/no-anonymous-default-export
export default {

  // ----- 业务术语和概念 -----
  // 多智能体系统术语
  agent: '智能体',
  multiAgent: '多智能体',
  expertSystem: '专家系统',
  decisionMaking: '决策制定',
  execution: '执行',
  collaboration: '协作',
  rolePlay: '角色扮演',
  // 行动空间术语
  actionSpace: '行动空间',
  actionRule: '行动规则',
  environmentVariable: '环境变量',
  monitoring: '监控',
  jointSpace: '联合空间',
  market: '市场',
  // 行动任务术语
  actionTask: '行动任务',
  parallelLab: '并行实验室',
  taskExecution: '任务执行',
  // 知识和记忆术语
  knowledgeBase: '知识库',
  memoryManagement: '记忆管理',
  memoryPartition: '记忆分区',
};
