// Auto-generated by scripts/split-locales.js — DO NOT EDIT THE BOILERPLATE.
// Namespace: history
// Language: zh-CN
// Add new keys for this namespace below. Keep keys consistent across
// languages — run `node scripts/check-i18n-keys.js` before commit.
// eslint-disable-next-line import/no-anonymous-default-export
export default {

  // ----- 历史记录页面翻译 -----
  'history.title': '对话历史',
  'history.subtitle': '查看和管理所有对话记录',
  'history.conversationId': '对话ID',
  'history.mode': '模式',
  'history.createdAt': '创建时间',
  'history.messageCount': '消息数量',
  'history.actions': '操作',
  'history.view': '查看',
  'history.delete': '删除',
  'history.loadFailed': '获取历史记录失败',
  'history.deleteFailed': '删除对话失败',
  'history.deleteSuccess': '删除成功',
  'history.conversationDetail': '对话详情',
  'history.conversationInfo': '对话信息',
  'history.conversationContent': '对话内容',
  'history.sequentialMode': '顺序对话',
  'history.panelMode': '面板对话',
};
