// Auto-generated by scripts/split-locales.js — DO NOT EDIT THE BOILERPLATE.
// Namespace: im
// Language: zh-CN
// Add new keys for this namespace below. Keep keys consistent across
// languages — run `node scripts/check-i18n-keys.js` before commit.
// eslint-disable-next-line import/no-anonymous-default-export
export default {

  // ----- IM 集成页面翻译 -----
  'imBot.title': 'IM 集成',
  'imBot.subtitle': '将 IM 机器人连接到智能体，实现即时通讯对话交互',
  'imBot.addBot': '添加机器人',
  'imBot.editBot': '编辑机器人',
  'imBot.name': '名称',
  'imBot.namePlaceholder': '例如：客服机器人',
  'imBot.platform': '平台',
  'imBot.agent': '智能体',
  'imBot.selectAgent': '选择智能体',
  'imBot.webhook': 'Webhook',
  'imBot.registered': '已注册',
  'imBot.notRegistered': '未注册',
  'imBot.status': '状态',
  'imBot.test': '测试连接',
  'imBot.registerWebhook': '注册 Webhook',
  'imBot.confirmDelete': '确定要删除此机器人吗？',
  'imBot.loadFailed': '加载机器人列表失败',
  'imBot.created': '机器人已创建',
  'imBot.updated': '机器人已更新',
  'imBot.deleted': '机器人已删除',
  'imBot.empty': '暂无配置的机器人',
  'imBot.triggerMode': '触发模式',
  'imBot.triggerAll': '所有消息',
  'imBot.triggerCommand': '仅命令 (/ask)',
  'imBot.actionTask': '行动任务',
  'imBot.selectActionTask': '请先选择行动任务',
  'imBot.selectTaskFirst': '请先选择行动任务',
  'imBot.loadDetailFailed': '加载机器人详情失败',
  'imBot.saveFailed': '保存失败',
  'imBot.deleteFailed': '删除失败',
  'imBot.updateFailed': '更新失败',
  'imBot.testFailed': '测试失败',
  'imBot.webhookFailed': 'Webhook 注册失败',
  'imBot.fieldRequired': '{{field}} 为必填项',
  'imBot.slackSetupHint': '保存后，请在 Slack App 的 Event Subscriptions 设置中配置 Request URL。',
};
