// Auto-generated by scripts/split-locales.js — DO NOT EDIT THE BOILERPLATE.
// Namespace: logs
// Language: zh-CN
// Add new keys for this namespace below. Keep keys consistent across
// languages — run `node scripts/check-i18n-keys.js` before commit.
// eslint-disable-next-line import/no-anonymous-default-export
export default {

  // ----- 运行日志页面翻译 -----
  'logs.title': '系统运行日志',
  'logs.subtitle': '查看系统运行日志，帮助诊断和解决问题',
  'logs.refresh': '刷新',
  'logs.download': '下载日志',
  'logs.clear': '清空',
  'logs.search': '搜索日志内容',
  'logs.logLevel': '日志级别',
  'logs.all': '全部',
  'logs.error': '错误',
  'logs.warning': '警告',
  'logs.info': '信息',
  'logs.debug': '调试',
  'logs.maxLines': '最大行数',
  'logs.autoRefresh': '自动刷新',
  'logs.scrollToTop': '滚动到顶部',
  'logs.scrollToBottom': '滚动到底部',
  'logs.fileInfo': '文件信息',
  'logs.filePath': '文件路径',
  'logs.fileSize': '文件大小',
  'logs.totalLines': '总行数',
  'logs.loadFailed': '加载日志失败',
  'logs.downloadFailed': '下载日志失败',
  'logs.clearFailed': '清空日志失败',
  'logs.stopAutoRefresh': '停止自动刷新',
  'logs.lines': '{{count}}行',
  'logs.loadedLines': '加载行数',
  'logs.filteredLines': '过滤后',
  'logs.loading': '加载日志中...',
  'logs.noMatches': '没有找到匹配的日志记录',
  'logs.clearFilters': '清除筛选',
};
