// Auto-generated by scripts/split-locales.js — DO NOT EDIT THE BOILERPLATE.
// Namespace: navigation
// Language: zh-CN
// Add new keys for this namespace below. Keep keys consistent across
// languages — run `node scripts/check-i18n-keys.js` before commit.
// eslint-disable-next-line import/no-anonymous-default-export
export default {

  // ----- 导航菜单 -----
  home: '首页',
  roles: '角色管理',
  tools: '工具管理',
  workspace: '项目空间',
  knowledgebase: '知识库管理',
  memory: '记忆管理',
  actionspace: '行动空间',
  actiontask: '行动任务',
  settings: '系统设置',

  // ----- 子菜单 -----
  'actionspace.overview': '行动空间概览',
  'actionspace.detail': '行动空间详情',
  'actionspace.rules': '行动规则',
  'actionspace.environment': '环境变量',
  'actionspace.monitoring': '监控中心',
  'actionspace.joint': '联合空间管理',
  'actionspace.market': '市场',
  'actiontask.overview': '行动任务概览',
  'actiontask.detail': '行动任务详情',
  'actiontask.parallellab': '并行实验室',
  'settings.general': '通用设置',
  'settings.models': '模型配置',
  'settings.mcp': 'MCP服务器',
  'settings.graph': '图增强设置',
  'settings.logs': '系统日志',
  'settings.im': 'IM 集成',
  'settings.about': '关于',
};
