// Auto-generated by scripts/split-locales.js — DO NOT EDIT THE BOILERPLATE.
// Namespace: roles
// Language: zh-CN
// Add new keys for this namespace below. Keep keys consistent across
// languages — run `node scripts/check-i18n-keys.js` before commit.
// eslint-disable-next-line import/no-anonymous-default-export
export default {

  // ----- 角色管理页面翻译 -----
  'roleManagement.title': '角色管理',
  'roleManagement.subtitle': '创建和管理智能体角色，配置模型参数、系统提示词和能力权限',
  'roleManagement.createRole': '创建角色',
  'roleManagement.editRole': '编辑角色',
  'roleManagement.importRole': '导入角色',
  'roleManagement.exportRole': '导出角色',

  // ----- 能力与工具管理页面翻译 -----
  'toolManagement.title': '能力与工具',
  'toolManagement.subtitle': '管理角色可用的工具和能力，提供API接口和函数调用能力，扩展智能体互动方式。要使用工具调用功能，请确保角色使用的模型在「模型配置」中已配置 function_calling 特性。',
  'toolManagement.createCapability': '创建能力',
  'toolManagement.editCapability': '编辑能力',
  'toolManagement.assignTools': '分配工具',
  'toolManagement.capabilityName': '能力名称',
  'toolManagement.capabilityType': '能力类型',
  'toolManagement.description': '描述',
  'toolManagement.associatedTools': '关联工具',
  'toolManagement.toolAssociation': '工具关联',
  'toolManagement.updateSuccess': '工具关联更新成功',
  'toolManagement.updateFailed': '更新工具关联失败',
  'toolManagement.createSuccess': '创建能力成功',
  'toolManagement.createFailed': '创建能力失败',
  'toolManagement.updateCapabilitySuccess': '更新能力成功',
  'toolManagement.updateCapabilityFailed': '更新能力失败',
};
