// Auto-generated by scripts/split-locales.js — DO NOT EDIT THE BOILERPLATE.
// Namespace: workspace
// Language: zh-CN
// Add new keys for this namespace below. Keep keys consistent across
// languages — run `node scripts/check-i18n-keys.js` before commit.
// eslint-disable-next-line import/no-anonymous-default-export
export default {

  // ----- 工作空间浏览器页面翻译 -----
  'workspace.title': '工作空间浏览器',
  'workspace.subtitle': '以文件浏览器的方式查看和管理所有行动任务的智能体工作空间和共享工作区，支持查看、编辑、删除',
  'workspace.browser': '工作空间浏览器',
  'workspace.template': '工作空间模板',
  'workspace.fileList': '工作空间文件列表',
  'workspace.files': '工作空间文件',
  'workspace.selectFirst': '请先选择一个工作空间',
  'workspace.noFiles': '该工作空间暂无文件',
  'workspace.uploadNotSupported': '只有行动任务工作空间支持文件上传',
  'workspace.loadFailed': '加载工作空间文件失败',
  'workspace.unknownType': '未知的工作空间类型',
  'workspace.upload': '上传文件',
  'workspace.refresh': '刷新',
  'workspace.taskWorkspace': '任务工作空间',
  'workspace.rootDirectory': '根目录',
  'workspace.rootUploadNotSupported': '根目录模式下不支持文件上传',

  // ----- 工作空间编辑器翻译 -----
  'workspaceEditor.save': '保存',
  'workspaceEditor.cancel': '取消',
  'workspaceEditor.editArea': '编辑区域',
  'workspaceEditor.previewArea': '预览区域',
  'workspaceEditor.emptyContent': '内容不能为空',
};
