// Auto-generated by scripts/split-locales.js — DO NOT EDIT THE BOILERPLATE.
// Namespace: business
// Language: en-US
// Add new keys for this namespace below. Keep keys consistent across
// languages — run `node scripts/check-i18n-keys.js` before commit.
// eslint-disable-next-line import/no-anonymous-default-export
export default {

  // ----- BUSINESS TERMS & CONCEPTS -----
  // Multi-Agent System Terms
  agent: 'Agent',
  multiAgent: 'Multi-Agent',
  expertSystem: 'Expert System',
  decisionMaking: 'Decision Making',
  execution: 'Execution',
  collaboration: 'Collaboration',
  rolePlay: 'Role Playing',
  // Action Space Terms
  actionSpace: 'Action Space',
  actionRule: 'Action Rule',
  environmentVariable: 'Environment Variable',
  monitoring: 'Monitoring',
  jointSpace: 'Joint Space',
  market: 'Market',
  // Action Task Terms
  actionTask: 'Action Task',
  parallelLab: 'Parallel Lab',
  taskExecution: 'Task Execution',
  // Knowledge & Memory Terms
  knowledgeBase: 'Knowledge Base',
  memoryManagement: 'Memory Management',
  memoryPartition: 'Memory Partition',

  // Role Selector (demo component)
  'roleSelector.title': 'Select Role',
  'roleSelector.placeholder': 'Select a role to start the conversation',
};
