// Auto-generated by scripts/split-locales.js — DO NOT EDIT THE BOILERPLATE.
// Namespace: history
// Language: en-US
// Add new keys for this namespace below. Keep keys consistent across
// languages — run `node scripts/check-i18n-keys.js` before commit.
// eslint-disable-next-line import/no-anonymous-default-export
export default {

  // ----- HISTORY PAGE TRANSLATIONS -----
  'history.title': 'Conversation History',
  'history.subtitle': 'View and manage all conversation records',
  'history.conversationId': 'Conversation ID',
  'history.mode': 'Mode',
  'history.createdAt': 'Created At',
  'history.messageCount': 'Message Count',
  'history.actions': 'Actions',
  'history.view': 'View',
  'history.delete': 'Delete',
  'history.loadFailed': 'Failed to load conversation history',
  'history.deleteFailed': 'Failed to delete conversation',
  'history.deleteSuccess': 'Deleted successfully',
  'history.conversationDetail': 'Conversation Details',
  'history.conversationInfo': 'Conversation Information',
  'history.conversationContent': 'Conversation Content',
  'history.sequentialMode': 'Sequential Conversation',
  'history.panelMode': 'Panel Conversation',
};
