// Auto-generated by scripts/split-locales.js — DO NOT EDIT THE BOILERPLATE.
// Namespace: im
// Language: en-US
// Add new keys for this namespace below. Keep keys consistent across
// languages — run `node scripts/check-i18n-keys.js` before commit.
// eslint-disable-next-line import/no-anonymous-default-export
export default {

  // ----- IM INTEGRATION PAGE TRANSLATIONS -----
  'imBot.title': 'IM Integration',
  'imBot.subtitle': 'Connect IM bots to your agents for conversational interactions',
  'imBot.addBot': 'Add Bot',
  'imBot.editBot': 'Edit Bot',
  'imBot.name': 'Name',
  'imBot.namePlaceholder': 'e.g. Customer Support Bot',
  'imBot.platform': 'Platform',
  'imBot.agent': 'Agent',
  'imBot.selectAgent': 'Select an agent',
  'imBot.webhook': 'Webhook',
  'imBot.registered': 'Registered',
  'imBot.notRegistered': 'Not Registered',
  'imBot.status': 'Status',
  'imBot.test': 'Test Connection',
  'imBot.registerWebhook': 'Register Webhook',
  'imBot.confirmDelete': 'Delete this bot?',
  'imBot.loadFailed': 'Failed to load bots',
  'imBot.created': 'Bot created',
  'imBot.updated': 'Bot updated',
  'imBot.deleted': 'Bot deleted',
  'imBot.empty': 'No bots configured yet',
  'imBot.triggerMode': 'Trigger Mode',
  'imBot.triggerAll': 'All Messages',
  'imBot.triggerCommand': 'Commands Only (/ask)',
  'imBot.actionTask': 'Action Task',
  'imBot.selectActionTask': 'Select an action task first',
  'imBot.selectTaskFirst': 'Please select an action task first',
  'imBot.loadDetailFailed': 'Failed to load bot details',
  'imBot.saveFailed': 'Save failed',
  'imBot.deleteFailed': 'Delete failed',
  'imBot.updateFailed': 'Update failed',
  'imBot.testFailed': 'Test failed',
  'imBot.webhookFailed': 'Webhook registration failed',
  'imBot.fieldRequired': '{{field}} is required',
  'imBot.slackSetupHint': 'After saving, configure the Request URL in your Slack App\'s Event Subscriptions settings.',
};
