// Auto-generated by scripts/split-locales.js — DO NOT EDIT BY HAND.
// Aggregates all namespaces for the "en-US" locale.
// - `namespaces` exposes each namespace separately (modern useTranslation('ns')).
// - Default export is the FLAT merged object, preserved for backwards
//   compatibility with the legacy single `translation` namespace.

import common from './common';
import navigation from './navigation';
import business from './business';
import home from './home';
import agents from './agents';
import roles from './roles';
import workspace from './workspace';
import actionspace from './actionspace';
import actiontask from './actiontask';
import parallellab from './parallellab';
import knowledgebase from './knowledgebase';
import memory from './memory';
import models from './models';
import settings from './settings';
import mcp from './mcp';
import im from './im';
import graph from './graph';
import logs from './logs';
import about from './about';
import oneclick from './oneclick';
import users from './users';
import account from './account';
import history from './history';
import setup from './setup';
import serviceCenter from './serviceCenter';

export const namespaces = {
  common: common,
  navigation: navigation,
  business: business,
  home: home,
  agents: agents,
  roles: roles,
  workspace: workspace,
  actionspace: actionspace,
  actiontask: actiontask,
  parallellab: parallellab,
  knowledgebase: knowledgebase,
  memory: memory,
  models: models,
  settings: settings,
  mcp: mcp,
  im: im,
  graph: graph,
  logs: logs,
  about: about,
  oneclick: oneclick,
  users: users,
  account: account,
  history: history,
  setup: setup,
  serviceCenter: serviceCenter,
};

const merged = {
  ...common,
  ...navigation,
  ...business,
  ...home,
  ...agents,
  ...roles,
  ...workspace,
  ...actionspace,
  ...actiontask,
  ...parallellab,
  ...knowledgebase,
  ...memory,
  ...models,
  ...settings,
  ...mcp,
  ...im,
  ...graph,
  ...logs,
  ...about,
  ...oneclick,
  ...users,
  ...account,
  ...history,
  ...setup,
  ...serviceCenter,
};

export default merged;
