// Auto-generated by scripts/split-locales.js — DO NOT EDIT THE BOILERPLATE.
// Namespace: logs
// Language: en-US
// Add new keys for this namespace below. Keep keys consistent across
// languages — run `node scripts/check-i18n-keys.js` before commit.
// eslint-disable-next-line import/no-anonymous-default-export
export default {

  // ----- LOGS PAGE TRANSLATIONS -----
  'logs.title': 'System Runtime Logs',
  'logs.subtitle': 'View system runtime logs to help diagnose and resolve issues',
  'logs.refresh': 'Refresh',
  'logs.download': 'Download Logs',
  'logs.clear': 'Clear',
  'logs.search': 'Search log content',
  'logs.logLevel': 'Log Level',
  'logs.all': 'All',
  'logs.error': 'Error',
  'logs.warning': 'Warning',
  'logs.info': 'Info',
  'logs.debug': 'Debug',
  'logs.maxLines': 'Max Lines',
  'logs.autoRefresh': 'Auto Refresh',
  'logs.scrollToTop': 'Scroll to Top',
  'logs.scrollToBottom': 'Scroll to Bottom',
  'logs.fileInfo': 'File Information',
  'logs.filePath': 'File Path',
  'logs.fileSize': 'File Size',
  'logs.totalLines': 'Total Lines',
  'logs.loadFailed': 'Failed to load logs',
  'logs.downloadFailed': 'Failed to download logs',
  'logs.clearFailed': 'Failed to clear logs',
  'logs.stopAutoRefresh': 'Stop Auto Refresh',
  'logs.lines': '{{count}} lines',
  'logs.loadedLines': 'Loaded Lines',
  'logs.filteredLines': 'Filtered',
  'logs.loading': 'Loading logs...',
  'logs.noMatches': 'No matching log entries found',
  'logs.clearFilters': 'Clear Filters',
};
