// Auto-generated by scripts/split-locales.js — DO NOT EDIT THE BOILERPLATE.
// Namespace: navigation
// Language: en-US
// Add new keys for this namespace below. Keep keys consistent across
// languages — run `node scripts/check-i18n-keys.js` before commit.
// eslint-disable-next-line import/no-anonymous-default-export
export default {

  // ----- NAVIGATION MENU -----
  home: 'Home',
  roles: 'Role Management',
  tools: 'Tool Management',
  workspace: 'Workspace',
  knowledgebase: 'Knowledge Base',
  memory: 'Memory Management',
  actionspace: 'Action Space',
  actiontask: 'Action Task',
  settings: 'Settings',

  // ----- SUB MENUS -----
  'actionspace.overview': 'Action Space Overview',
  'actionspace.detail': 'Action Space Detail',
  'actionspace.rules': 'Action Rules',
  'actionspace.environment': 'Environment Variables',
  'actionspace.monitoring': 'Monitoring Center',
  'actionspace.joint': 'Joint Space Management',
  'actionspace.market': 'Market',
  'actiontask.overview': 'Action Task Overview',
  'actiontask.detail': 'Action Task Detail',
  'actiontask.parallellab': 'Parallel Lab',
  'settings.general': 'General Settings',
  'settings.models': 'Model Configuration',
  'settings.mcp': 'MCP Servers',
  'settings.graph': 'Graph Enhancement',
  'settings.logs': 'System Logs',
  'settings.im': 'IM Integration',
  'settings.about': 'About',
};
