// Auto-generated by scripts/split-locales.js — DO NOT EDIT THE BOILERPLATE.
// Namespace: roles
// Language: en-US
// Add new keys for this namespace below. Keep keys consistent across
// languages — run `node scripts/check-i18n-keys.js` before commit.
// eslint-disable-next-line import/no-anonymous-default-export
export default {

  // ----- ROLE MANAGEMENT PAGE TRANSLATIONS -----
  'roleManagement.title': 'Role Management',
  'roleManagement.subtitle': 'Create and manage agent roles, configure model parameters, system prompts and capability permissions',
  'roleManagement.createRole': 'Create Role',
  'roleManagement.editRole': 'Edit Role',
  'roleManagement.importRole': 'Import Role',
  'roleManagement.exportRole': 'Export Role',

  // ----- CAPABILITIES AND TOOLS MANAGEMENT PAGE TRANSLATIONS -----
  'toolManagement.title': 'Capabilities & Tools',
  'toolManagement.subtitle': 'Manage available tools and capabilities for roles, providing API interfaces and function calling capabilities to extend agent interaction methods. To use tool calling features, ensure that the model used by the role has the function_calling capability configured in "Model Configuration".',
  'toolManagement.createCapability': 'Create Capability',
  'toolManagement.editCapability': 'Edit Capability',
  'toolManagement.assignTools': 'Assign Tools',
  'toolManagement.capabilityName': 'Capability Name',
  'toolManagement.capabilityType': 'Capability Type',
  'toolManagement.description': 'Description',
  'toolManagement.associatedTools': 'Associated Tools',
  'toolManagement.toolAssociation': 'Tool Association',
  'toolManagement.updateSuccess': 'Tool association updated successfully',
  'toolManagement.updateFailed': 'Failed to update tool association',
  'toolManagement.createSuccess': 'Capability created successfully',
  'toolManagement.createFailed': 'Failed to create capability',
  'toolManagement.updateCapabilitySuccess': 'Capability updated successfully',
  'toolManagement.updateCapabilityFailed': 'Failed to update capability',
};
