// Auto-generated by scripts/split-locales.js — DO NOT EDIT THE BOILERPLATE.
// Namespace: workspace
// Language: en-US
// Add new keys for this namespace below. Keep keys consistent across
// languages — run `node scripts/check-i18n-keys.js` before commit.
// eslint-disable-next-line import/no-anonymous-default-export
export default {

  // ----- WORKSPACE BROWSER PAGE TRANSLATIONS -----
  'workspace.title': 'Workspace Browser',
  'workspace.subtitle': 'View and manage all action task agent workspaces and shared workspaces in a file browser interface, supporting view, edit, and delete operations',
  'workspace.browser': 'Workspace Browser',
  'workspace.template': 'Workspace Templates',
  'workspace.fileList': 'Workspace File List',
  'workspace.files': 'Workspace Files',
  'workspace.selectFirst': 'Please select a workspace first',
  'workspace.noFiles': 'No files in this workspace',
  'workspace.uploadNotSupported': 'Only action task workspaces support file upload',
  'workspace.loadFailed': 'Failed to load workspace files',
  'workspace.unknownType': 'Unknown workspace type',
  'workspace.upload': 'Upload File',
  'workspace.refresh': 'Refresh',
  'workspace.taskWorkspace': 'Task Workspace',
  'workspace.rootDirectory': 'Root Directory',
  'workspace.rootUploadNotSupported': 'File upload is not supported in root directory mode',

  // ----- WORKSPACE EDITOR TRANSLATIONS -----
  'workspaceEditor.save': 'Save',
  'workspaceEditor.cancel': 'Cancel',
  'workspaceEditor.editArea': 'Edit Area',
  'workspaceEditor.previewArea': 'Preview Area',
  'workspaceEditor.emptyContent': 'Content cannot be empty',
};
