"""cascade delete action_task to conversations

Revision ID: a51a7c66578c
Revises: fedea876a659
Create Date: 2026-05-18 17:57:49.659806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a51a7c66578c'
down_revision: Union[str, Sequence[str], None] = 'fedea876a659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add ON DELETE CASCADE to conversations.action_task_id.

    Background: see docs/agents/failures/2026-05-18-action-task-delete-cascade-default.md.
    The original FK had no ondelete rule, so SQLAlchemy's default cascade
    behaviour tried to NULL the child FK on parent delete and collided
    with the NOT NULL constraint (MariaDB 1048).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('conversations_ibfk_1'), 'conversations', type_='foreignkey')
    op.create_foreign_key(
        'conversations_action_task_id_fkey',
        'conversations',
        'action_tasks',
        ['action_task_id'],
        ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert to the original FK without ON DELETE rule."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversations_action_task_id_fkey', 'conversations', type_='foreignkey')
    op.create_foreign_key(
        op.f('conversations_ibfk_1'),
        'conversations',
        'action_tasks',
        ['action_task_id'],
        ['id'],
    )
    # ### end Alembic commands ###
